# © 2018 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "contacts_config_menu_moved_right",
        "contacts_config_sale_manager",
        # "forward_sorting_area",
        "google_partner_address",
        # "partner_affiliate_invoicing_address",
        # "partner_autocomplete_disable",
        # "partner_category_type",
        # "partner_change_parent",
        # "partner_change_parent_affiliate",
        "partner_city_tree_view",
        # "partner_client_type",
        # "partner_contact_type_visible",
        # "partner_duplicate_mgmt",
        # "partner_duplicate_multi_phone",
        # "partner_duplicate_multi_relation",
        # "partner_edit_group",
        # "partner_filters_simplified",
        # "partner_firstname_before_lastname",
        # "partner_full_text_search",
        # "partner_gst_qst",
        # "partner_key_date",
        # "partner_multi_phone",
        # "partner_multi_relation_note",
        # "partner_multi_relation_strength",
        # "partner_multi_relation_work",
        # "partner_naics_code",
        # "partner_name_no_shortcut",
        # "partner_no_vat",
        # "partner_no_vat_website_sale",
        # "partner_phone_no_envelope",
        # "partner_phone_validation",
        # "partner_portal_access_group",
        # "partner_reference",
        # "partner_unique_email",
        # "partner_user_auto_assign",
        "partner_validation",
        # "partner_validation_purchase",
        # "partner_validation_sale",
        # "partner_website_domain_only",
        # "res_partner_bank_shared_account",
    ],
    "installable": False,
}
