# © 2018 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    'name': 'Main Module',
    'version': '1.0.0',
    'author': 'Numigi',
    'maintainer': 'Numigi',
    'website': 'https://www.numigi.com',
    'license': 'LGPL-3',
    'category': 'Other',
    'summary': 'Install all addons required for testing.',
    'depends': [
        'google_partner_address',
        'partner_change_parent',
        'partner_change_parent_affiliate',
        'partner_duplicate_mgmt',
        'partner_duplicate_multi_phone',
        'partner_duplicate_multi_relation',
        'partner_edit_group',
        'partner_firstname_before_lastname',
        'partner_key_date',
        'partner_multi_phone',
        'partner_multi_relation_note',
        'partner_multi_relation_strength',
        'partner_multi_relation_work',
        'partner_name_no_shortcut',
        'partner_phone_no_envelope',
        'partner_phone_validation',
        'partner_reference',
        'partner_unique_email',
        'partner_website_domain_only',
        'res_partner_bank_shared_account',
    ],
    'installable': True,
}
