version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./.log:/var/log/odoo
      - ./partner_filters_simplified:/mnt/extra-addons/partner_filters_simplified
    ports:
      - "8070:8069"
      - "8072:8071"
    depends_on:
      - db
    command: odoo
    environment:
      - LOG_ODOO=/var/log/odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

volumes:
  odoo-web-data:
  odoo-db-data:
